### ISSUE TITLE
Main Window

### ISSUE THREAD

**Issue by Erase01** [Erase01/Math-Project#2]
# ToDo:
- [ ] Menu
- [ ] Space for functional graph
- [ ] Help button
- [ ] Buttons for zooming in and out of the functional graph

## Optional:
- [ ] Button for returning to the center of the diagram
