### ISSUE TITLE
Exponential module

### ISSUE THREAD

**Issue by Erase01** [Erase01/Math-Project#6]
## TODO:

- [ ] dynamic adaptation of the graph large
- [ ] scrolling in the graph
- [ ] zoom in/out
